version: 2.1

orbs:
  windows: circleci/windows@2.2.0

parameters:
  updated-sdk:
    type: boolean
    default: true

jobs:
  release:
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "ApertureSDK.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "ApertureSDK.csproj" }}
      - run:
          name: "Package Application"
          command: dotnet.exe pack

workflows:
  version: 2

  publish-release:
    when:
      or:
        - equal: [main, << pipeline.git.branch >>]
        - << pipeline.parameters.updated-sdk >>
    jobs:
      - publish-release:
          name: verify-publish-release
