version: 2.1

orbs:
  windows: circleci/windows@5.0.0

parameters:
  updated-sdk:
    type: boolean
    default: true

jobs:
  release:
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "ApertureSDK.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "ApertureSDK.csproj" }}
      - run:
          name: "Package Application"
          command: dotnet.exe pack
      - run:
          name: "Publish Application"
          command: dotnet.exe nuget push --source C:\Users\circleci\project\bin\Debug\ApertureSDK* --api-key $NUGET_API_TOKEN --source https://api.nuget.org/v3/index.json

workflows:
  version: 2

  publish-release:
    when: << pipeline.parameters.updated-sdk >>
    jobs:
      - release:
          name: verify-publish-release
